abstract final class Routes {
  static const home = '/home';
  static const login = '/login';
  static const welcome = '/welcome';
  static const estateHome = '/estate-home';
  static const estateSelect = '/estate-select';
  static const userProfile = '/user-profile';
  static const estateDashboard = '/estate-dashboard';
  static const estateDashboardRelative = 'estate-dashboard';
  static const estateCreate = '/$estateCreateRelative';
  static const estateCreateRelative = 'estate-create';
  static const estateJoin = '/$estateJoinRelative';
  static const estateJoinRelative = 'estate-join';
  static const estateJoinPending = '/$estateJoinPendingRelative';
  static const estateJoinPendingRelative = 'estate-join-pending';
  static const estateDetails = '/$estateDetailsRelative';
  static const estateDetailsRelative = 'estate-details';
  static const estateMembers = '/$estateMembersRelative';
  static const estateMembersRelative = 'estate-members';
  static const estateMembersPending = '/$estateMembersPendingRelative';
  static const estateMembersPendingRelative = 'pending-members';
  static const estateNotices = '/$estateNoticesRelative';
  static const estateNoticesRelative = 'estate-notices';
  static const estateTreasury = '/$estateTreasuryRelative';
  static const estateTreasuryRelative = 'estate-treasury';
  static const estateDocuments = '/$estateDocumentsRelative';
  static const estateDocumentsRelative = 'estate-documents';
}
